import { Pane } from 'tweakpane';
export class LiveEditor {
  constructor(configManager,onChange){this.cm=configManager;this.pane=new Pane({title:'Universo 360°',expanded:true});this.pane.element.parentElement.classList.add('editor-shell');this.pane.hidden=true;const c=this.cm.config;this.add('GENERAL',c.general,[['exposure',{min:.6,max:1.8,step:.01}]]);this.add('CÁMARA 360°',c.camera360,[['autoRotate',{}],['autoRotateSpeed',{min:0,max:1,step:.01}],['damping',{min:.01,max:.2,step:.01}],['minDistance',{min:3,max:12,step:.1}],['maxDistance',{min:8,max:30,step:.1}]]);this.add('GALAXIA',c.galaxy,[['radius',{min:5,max:16,step:.1}],['height',{min:2,max:14,step:.1}],['rotationSpeed',{min:0,max:.03,step:.001}]]);this.add('AGUJERO NEGRO',c.blackHole,[['size',{min:.5,max:2,step:.01}],['diskSpeed',{min:0,max:.3,step:.001}],['lensingStrength',{min:0,max:1.5,step:.01}]]);this.add('BLOOM',c.bloom,[['strength',{min:0,max:2.5,step:.01}],['radius',{min:0,max:1,step:.01}],['threshold',{min:0,max:1,step:.01}]]);this.add('FLORES',c.flowers,[['floatAmplitude',{min:0,max:.5,step:.01}],['floatSpeed',{min:0,max:1,step:.01}]]);this.add('CONTENIDO',c.content,[['title',{}],['prompt',{}],['dedication',{}]]);this.pane.on('change',()=>onChange(c));const actions=this.pane.addFolder({title:'CONFIGURACIÓN V2'});actions.addButton({title:'Guardar'}).on('click',()=>this.cm.save());actions.addButton({title:'Restaurar'}).on('click',()=>{this.cm.reset();location.reload();});actions.addButton({title:'Exportar JSON'}).on('click',()=>this.download());actions.addButton({title:'Importar JSON'}).on('click',()=>this.pick());}
  add(title,obj,items){const folder=this.pane.addFolder({title});for(const[key,options]of items)folder.addBinding(obj,key,options);}
  toggle(force){this.pane.hidden=force===undefined?!this.pane.hidden:!force;}
  download(){const anchor=document.createElement('a');anchor.href=URL.createObjectURL(new Blob([this.cm.export()],{type:'application/json'}));anchor.download='yellow-universe-v2-config.json';anchor.click();URL.revokeObjectURL(anchor.href);}
  pick(){const input=document.createElement('input');input.type='file';input.accept='.json';input.onchange=async()=>{try{this.cm.import(await input.files[0].text());location.reload();}catch{alert('Configuración no válida.');}};input.click();}
  dispose(){this.pane.dispose();}
}
