import '../styles/v2.css';
import * as THREE from 'three';
import { gsap } from 'gsap';
import { Renderer } from './Renderer.js'; import { Camera } from './Camera.js'; import { CameraRig } from './CameraRig.js'; import { Clock } from './Clock.js'; import { SceneManager, STATES } from './SceneManager.js'; import { AssetManager } from './AssetManager.js'; import { PerformanceManager } from './PerformanceManager.js'; import { ConfigManager } from './ConfigManager.js'; import { InputManager } from './InputManager.js'; import { AudioManager } from './AudioManager.js'; import { ResourceTracker } from './ResourceTracker.js'; import { InteractiveRegistry } from './InteractiveRegistry.js';
import { Sunflower } from '../objects/Sunflower.js'; import { SunflowerParticleCloud } from '../objects/SunflowerParticleCloud.js'; import { TextParticleCloud } from '../objects/TextParticleCloud.js'; import { BlackHole } from '../objects/BlackHole.js'; import { FlowerInstanceSystem } from '../objects/FlowerInstanceSystem.js'; import { SpatialTextSystem } from '../objects/SpatialTextSystem.js'; import { GalaxyField } from '../objects/GalaxyField.js'; import { ParticlePool } from '../objects/ParticlePool.js'; import { configureCloudForUniverse } from '../objects/GalaxyDistribution.js';
import { ParticleMorph } from '../experience/ParticleMorph.js'; import { PostProcessing } from '../postprocessing/PostProcessing.js'; import { UniverseRaycaster } from '../interactions/UniverseRaycaster.js'; import { KeyboardController } from '../interactions/KeyboardController.js';
import { LoadingOverlay } from '../ui/LoadingOverlay.js'; import { IntroPrompt } from '../ui/IntroPrompt.js'; import { MessageOverlay } from '../ui/MessageOverlay.js'; import { QuoteOverlay } from '../ui/QuoteOverlay.js'; import { AudioControl } from '../ui/AudioControl.js'; import { LiveEditor } from '../ui/LiveEditor.js'; import { ExploreControls } from '../ui/ExploreControls.js';
import { contentCatalog } from '../data/contentCatalog.js'; import { UniverseLayout } from '../utils/UniverseLayout.js';

export class App {
  constructor({canvas,container,initialConfig}){this.canvas=canvas;this.ui=container;this.cm=new ConfigManager(initialConfig);this.config=this.cm.config;this.tracker=new ResourceTracker();this.performance=new PerformanceManager();this.profile=this.performance.detect();this.scene=new THREE.Scene();this.scene.background=new THREE.Color(this.config.general.background);this.camera=new Camera(this.config);this.camera.instance.position.set(0,0,this.config.camera.distance);this.camera.instance.lookAt(0,0,0);this.renderer=new Renderer(canvas,this.config,this.profile);this.clock=new Clock();this.assets=new AssetManager();this.states=new SceneManager();this.input=new InputManager(canvas,this.tracker);this.audio=new AudioManager(this.config);this.running=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||this.config.accessibility.reducedMotion;this.pointerDown={x:0,y:0};}
  async init(){this.loading=new LoadingOverlay(this.ui);const timer=setTimeout(()=>this.loading.show(),500);const base=import.meta.env.BASE_URL;const [hero,sunflowerAtlas,bouquetAtlas]=await Promise.all([this.assets.loadTexture('sunflowerHero',`${base}assets/flowers/sunflower-hero-v2.png`),this.assets.loadTexture('sunflowerAtlas',`${base}assets/flowers/sunflower-atlas-v2.png`),this.assets.loadTexture('bouquetAtlas',`${base}assets/flowers/bouquet-atlas-v2.png`)]);clearTimeout(timer);if(!hero||!sunflowerAtlas||!bouquetAtlas)throw new Error('No se pudo cargar la familia de flores V2.');
    this.sunflower=new Sunflower(hero);this.cloud=new SunflowerParticleCloud({count:this.profile.stars,seed:this.config.galaxy.seed,pointScale:innerHeight*.08});configureCloudForUniverse(this.cloud,{seed:this.config.galaxy.seed,radius:this.config.galaxy.radius,height:this.config.galaxy.height});this.cloud.visible=false;this.textCloud=new TextParticleCloud({text:this.config.content.title});this.textCloud.visible=false;
    this.galaxy=new GalaxyField({cloud:this.cloud,profile:this.profile,config:this.config});this.blackHole=new BlackHole(this.config.blackHole,this.profile.name);this.blackHole.reset();
    const available=contentCatalog.list(this.profile.name),flowerEntries=available.filter(entry=>entry.type!=='phrase').slice(0,this.profile.flowers),phraseEntries=available.filter(entry=>entry.type==='phrase').slice(0,this.profile.texts);await SpatialTextSystem.preload(`${this.config.content.title} ${phraseEntries.map(entry=>entry.label).join(' ')}`);const layout=new UniverseLayout({seed:this.config.galaxy.seed,radius:this.config.galaxy.radius,height:this.config.galaxy.height});this.flowers=new FlowerInstanceSystem({sunflowerAtlas,bouquetAtlas,entries:flowerEntries,layout,config:this.config});this.spatialText=new SpatialTextSystem({entries:phraseEntries,layout:new UniverseLayout({seed:this.config.galaxy.seed+99,radius:this.config.galaxy.radius,height:this.config.galaxy.height})});this.spatialText.reveal(0);this.pool=new ParticlePool(240);
    this.scene.add(this.sunflower.object,this.cloud,this.textCloud,this.galaxy,this.blackHole,this.flowers,this.spatialText,this.pool.object);
    this.registry=new InteractiveRegistry();this.flowers.register(this.registry);this.spatialText.register(this.registry);this.universeRaycaster=new UniverseRaycaster(this.camera.instance,this.registry,selection=>this.openCard(selection));
    this.post=new PostProcessing({renderer:this.renderer.instance,scene:this.scene,camera:this.camera.instance,blackHole:this.blackHole,quality:this.profile.name,config:{bloomStrength:this.config.bloom.strength,bloomRadius:this.config.bloom.radius,bloomThreshold:this.config.bloom.threshold,lensingStrength:this.config.blackHole.lensingStrength,exposure:this.config.general.exposure}});
    this.cameraRig=new CameraRig(this.camera.instance,this.canvas,this.config,this.reduced);this.morph=new ParticleMorph({cloud:this.cloud,duration:this.config.narrative.explosionDuration,reducedMotion:this.reduced,onComplete:()=>this.showMessage()});this.prompt=new IntroPrompt(this.ui,this.config.content.prompt);this.message=new MessageOverlay(this.ui,this.config.content.title);this.quote=new QuoteOverlay(this.ui,()=>this.closeCard());this.explore=new ExploreControls(this.ui,()=>this.cameraRig.center());this.audioControl=new AudioControl(this.ui,this.audio);this.editor=new LiveEditor(this.cm,config=>this.applyConfig(config));this.keyboard=new KeyboardController({editor:()=>this.editor.toggle(),audio:()=>this.audio.toggle(),restart:()=>this.restart(),escape:()=>this.quote.visible?this.closeCard():this.editor.toggle(false)});
    this.input.addEventListener('activate',event=>this.activate(event.detail));this.tracker.trackEvent(this.canvas,'pointerdown',event=>{this.pointerDown.x=event.clientX;this.pointerDown.y=event.clientY;},{passive:true},'v2-pointer');this.tracker.trackEvent(this.canvas,'pointercancel',()=>{this.pointerDown.x=Number.NaN;this.pointerDown.y=Number.NaN;},{passive:true},'v2-pointer');this.tracker.trackEvent(this.canvas,'pointerup',event=>{if(this.states.getState()!==STATES.UNIVERSE)return;if(Math.hypot(event.clientX-this.pointerDown.x,event.clientY-this.pointerDown.y)<9)this.universeRaycaster.pick(event.clientX,event.clientY);},{passive:true},'v2-pointer');this.tracker.trackEvent(window,'resize',()=>this.resize(),{passive:true},'v2-window');this.tracker.trackEvent(document,'visibilitychange',()=>{this.running=!document.hidden;if(this.running)this.loop();},false,'v2-window');this.resize();this.loading.hide();return this;
  }
  start(){this.states.transitionTo(STATES.INTRO);this.running=true;this.sunflower.reveal(0);const value={v:0};gsap.to(value,{v:1,duration:this.config.narrative.introDuration,delay:this.config.narrative.introDelay,ease:'power3.out',onUpdate:()=>this.sunflower.reveal(value.v),onComplete:()=>this.prompt.show()});this.loop();}
  activate(){if(this.states.getState()===STATES.INTRO)this.beginMorph();}
  beginMorph(){if(!this.states.transitionTo(STATES.MORPH))return;this.prompt.hide();this.audio.ensure();this.cloud.visible=true;this.morph.enter({},{});const value={p:0};gsap.to(value,{p:1,duration:.82,onUpdate:()=>this.sunflower.hide(value.p),onComplete:()=>{this.sunflower.object.visible=false;}});}
  showMessage(){this.states.transitionTo(STATES.MESSAGE);this.textCloud.visible=true;this.textCloud.setOpacity(0);const value={opacity:0};gsap.to(value,{opacity:1,duration:.8,ease:'power2.out',onUpdate:()=>this.textCloud.setOpacity(value.opacity)});this.message.show();clearTimeout(this.messageTimer);this.messageTimer=setTimeout(()=>{this.message.hide();gsap.to(value,{opacity:0,duration:.65,onUpdate:()=>this.textCloud.setOpacity(value.opacity),onComplete:()=>{this.textCloud.visible=false;this.travel();}});},this.config.narrative.messageDuration*1000);}
  travel(){this.states.transitionTo(STATES.TRAVEL);this.galaxy.reveal(.15);this.cameraRig.beginTravel();const start=this.camera.instance.position.clone(),end=new THREE.Vector3(0,3.2,this.config.camera.distance),value={p:0};gsap.to(value,{p:1,duration:this.reduced?.9:this.config.narrative.travelDuration,ease:'power2.inOut',onUpdate:()=>{this.camera.instance.position.lerpVectors(start,end,value.p);this.camera.instance.lookAt(0,0,0);this.galaxy.reveal(value.p);},onComplete:()=>this.revealUniverse()});}
  revealUniverse(){this.states.transitionTo(STATES.BLACK_HOLE_REVEAL);const value={p:0};gsap.to(value,{p:1,duration:this.config.narrative.blackHoleRevealDuration,ease:'power2.out',onUpdate:()=>{this.blackHole.reveal(value.p);this.flowers.reveal(Math.max(0,(value.p-.18)/.82));this.spatialText.reveal(Math.max(0,(value.p-.36)/.64));},onComplete:()=>{this.states.transitionTo(STATES.UNIVERSE);this.cameraRig.enterOrbit();this.explore.show();}});}
  openCard(selection){if(this.states.getState()!==STATES.UNIVERSE)return;const entry=contentCatalog.get(selection.id);if(!entry)return;this.states.transitionTo(STATES.QUOTE_FOCUS);this.selected=selection;this.flowers.focus(selection,true);this.pool.burst(selection.point);this.cameraRig.focus(selection.worldPosition,selection.radius,()=>this.quote.open(entry));}
  closeCard(){this.quote.close();this.flowers.focus(this.selected,false);this.cameraRig.restore(()=>{this.selected=null;if(this.states.getState()===STATES.QUOTE_FOCUS)this.states.transitionTo(STATES.UNIVERSE);});}
  applyConfig(config){this.renderer.instance.toneMappingExposure=config.general.exposure;this.camera.instance.fov=config.camera.fov;this.camera.instance.updateProjectionMatrix();this.cameraRig.applyConfig(config);this.flowers.applyConfig(config);this.blackHole.applyConfig(config.blackHole);this.post.applyConfig({bloomStrength:config.bloom.strength,bloomRadius:config.bloom.radius,bloomThreshold:config.bloom.threshold,lensingStrength:config.blackHole.lensingStrength,exposure:config.general.exposure,quality:this.profile.name});}
  update(frame){if(this.states.getState()===STATES.INTRO)this.sunflower.update(frame.elapsed,true);this.cloud.update(frame.elapsed);this.textCloud.update(frame.elapsed);this.galaxy.update(frame);this.blackHole.update(frame);this.flowers.update(frame.elapsed);this.spatialText.update(frame.elapsed,this.camera.instance);this.pool.update(frame.delta);this.morph.update(frame);this.cameraRig.update(frame);if(this.performance.sample(frame.delta)){this.profile=this.performance.profile;this.renderer.resize(this.profile);this.post.setQuality(this.profile.name);this.blackHole.setQuality?.(this.profile.name);this.cloud.geometry.setDrawRange(0,Math.min(this.profile.stars,this.cloud.geometry.getAttribute('position').count));this.galaxy.setQuality(this.profile);this.flowers.setQuality(this.profile);this.spatialText.setQuality(this.profile);}this.post.render(frame.delta);}
  loop=()=>{if(!this.running)return;const frame=this.clock.tick();this.update(frame);requestAnimationFrame(this.loop);};
  resize(){this.renderer.resize(this.profile);this.camera.resize();const pixelRatio=this.renderer.instance.getPixelRatio();this.post?.resize(innerWidth,innerHeight,pixelRatio);this.cloud?.setPixelRatio(pixelRatio);this.textCloud?.setPixelRatio(pixelRatio);this.galaxy?.setPixelRatio(pixelRatio);}
  restart(){clearTimeout(this.messageTimer);gsap.globalTimeline.clear();this.quote.close();this.flowers.focus(this.selected,false);this.selected=null;this.explore.hide();this.states.restart();this.cameraRig.reset(this.config.camera.distance);this.sunflower.object.visible=true;this.sunflower.reveal(1);this.cloud.visible=false;this.cloud.reset();this.textCloud.visible=false;this.textCloud.setOpacity(0);this.galaxy.reveal(0);this.blackHole.reset();this.flowers.reveal(0);this.spatialText.reveal(0);this.prompt.show();}
  destroy(){this.running=false;clearTimeout(this.messageTimer);gsap.globalTimeline.clear();this.keyboard?.dispose();this.editor?.dispose();this.explore?.dispose();this.quote?.dispose();this.prompt?.dispose();this.message?.dispose();this.audioControl?.dispose();this.cameraRig?.dispose();this.audio.dispose();this.post?.dispose();this.sunflower?.dispose();this.cloud?.dispose();this.textCloud?.dispose();this.galaxy?.dispose();this.blackHole?.dispose();this.flowers?.dispose();this.spatialText?.dispose();this.pool?.dispose();this.registry?.clear();this.assets.dispose();this.tracker.disposeAll();this.renderer.dispose();}
}
