import * as THREE from 'three';import {gsap} from 'gsap';
import {Renderer} from './Renderer.js';import {Camera} from './Camera.js';import {Clock} from './Clock.js';import {SceneManager,STATES} from './SceneManager.js';import {AssetManager} from './AssetManager.js';import {PerformanceManager} from './PerformanceManager.js';import {ConfigManager} from './ConfigManager.js';import {InputManager} from './InputManager.js';import {AudioManager} from './AudioManager.js';import {ResourceTracker} from './ResourceTracker.js';
import {Sunflower} from '../objects/Sunflower.js';import {SunflowerParticleCloud} from '../objects/SunflowerParticleCloud.js';import {TextParticleCloud} from '../objects/TextParticleCloud.js';import {DustField} from '../objects/DustField.js';import {BlackHole} from '../objects/BlackHole.js';import {OrbitingFlowers} from '../objects/OrbitingFlowers.js';import {ParticlePool} from '../objects/ParticlePool.js';import {ParticleMorph} from '../experience/ParticleMorph.js';import {PostProcessing} from '../postprocessing/PostProcessing.js';import {FlowerRaycaster} from '../interactions/FlowerRaycaster.js';import {KeyboardController} from '../interactions/KeyboardController.js';
import {LoadingOverlay} from '../ui/LoadingOverlay.js';import {IntroPrompt} from '../ui/IntroPrompt.js';import {MessageOverlay} from '../ui/MessageOverlay.js';import {QuoteOverlay} from '../ui/QuoteOverlay.js';import {AudioControl} from '../ui/AudioControl.js';import {LiveEditor} from '../ui/LiveEditor.js';import {quotes} from '../data/quotes.js';
export class App{constructor({canvas,container,initialConfig}){this.canvas=canvas;this.ui=container;this.cm=new ConfigManager(initialConfig);this.config=this.cm.config;this.tracker=new ResourceTracker();this.performance=new PerformanceManager();this.profile=this.performance.detect();this.scene=new THREE.Scene();this.scene.background=new THREE.Color(this.config.general.background);this.camera=new Camera(this.config);this.renderer=new Renderer(canvas,this.config,this.profile);this.clock=new Clock();this.assets=new AssetManager();this.states=new SceneManager();this.input=new InputManager(canvas,this.tracker);this.audio=new AudioManager(this.config);this.running=false;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches||this.config.accessibility.reducedMotion;}
async init(){this.loading=new LoadingOverlay(this.ui);const timer=setTimeout(()=>this.loading.show(),500);const texture=await this.assets.loadTexture('sunflower',`${import.meta.env.BASE_URL}assets/flowers/sunflower-hero.png`);clearTimeout(timer);if(!texture)throw new Error('No se pudo cargar el girasol.');this.sunflower=new Sunflower(texture);this.cloud=new SunflowerParticleCloud({count:this.profile.stars,pointScale:innerHeight*.08});this.cloud.visible=false;this.textCloud=new TextParticleCloud({text:this.config.content.title});this.textCloud.visible=false;this.dust=new DustField({count:this.profile.dust});this.dust.visible=false;this.blackHole=new BlackHole(this.config.blackHole,this.profile.name);this.blackHole.position.set(0,.1,-8);this.flowers=new OrbitingFlowers(texture,Math.min(this.config.flowers.count,this.profile.flowers));this.pool=new ParticlePool();this.scene.add(this.sunflower.object,this.cloud,this.textCloud,this.dust,this.blackHole,this.flowers.group,this.pool.object);this.post=new PostProcessing({renderer:this.renderer.instance,scene:this.scene,camera:this.camera.instance,blackHole:this.blackHole,quality:this.profile.name,config:{bloomStrength:this.config.bloom.strength,bloomRadius:this.config.bloom.radius,bloomThreshold:this.config.bloom.threshold,lensingStrength:this.config.blackHole.lensingStrength*.05,exposure:this.config.general.exposure}});this.morph=new ParticleMorph({cloud:this.cloud,duration:this.config.timing.explosionDuration,reducedMotion:this.reduced,onComplete:()=>this.showMessage()});this.prompt=new IntroPrompt(this.ui,this.config.content.prompt);this.message=new MessageOverlay(this.ui,this.config.content.title);this.quote=new QuoteOverlay(this.ui,()=>this.closeQuote());this.audioControl=new AudioControl(this.ui,this.audio);this.editor=new LiveEditor(this.cm,c=>this.applyConfig(c));this.raycaster=new FlowerRaycaster(this.camera.instance,this.flowers,(flower,point)=>this.openQuote(flower,point));this.keyboard=new KeyboardController({editor:()=>this.editor.toggle(),audio:()=>this.audio.toggle(),restart:()=>this.restart(),escape:()=>this.quote.visible?this.closeQuote():this.editor.toggle(false)});this.input.addEventListener('activate',e=>this.activate(e.detail));addEventListener('resize',()=>this.resize(),{passive:true});document.addEventListener('visibilitychange',()=>{this.running=!document.hidden;if(this.running)this.loop();});this.resize();this.loading.hide();return this;}
start(){this.states.transitionTo(STATES.INTRO);this.running=true;this.sunflower.reveal(0);const state={v:0};gsap.to(state,{v:1,duration:this.config.timing.introDuration,delay:this.config.timing.introDelay,ease:'power3.out',onUpdate:()=>this.sunflower.reveal(state.v),onComplete:()=>this.prompt.show()});this.loop();}
activate(event){const state=this.states.getState();if(state===STATES.INTRO){this.beginMorph();return;}if(state===STATES.UNIVERSE){const x=event.clientX/innerWidth*2-1,y=event.clientY/innerHeight*2-1;this.raycaster.pick(x,y);}}
beginMorph(){if(!this.states.transitionTo(STATES.MORPH))return;this.prompt.hide();this.audio.ensure();this.cloud.visible=true;this.morph.enter({},{});const v={p:0};gsap.to(v,{p:1,duration:.8,onUpdate:()=>this.sunflower.hide(v.p),onComplete:()=>{this.sunflower.object.visible=false;}});}
showMessage(){this.states.transitionTo(STATES.MESSAGE);this.textCloud.visible=true;this.textCloud.setOpacity(0);const particles={opacity:0};gsap.to(particles,{opacity:1,duration:.8,ease:'power2.out',onUpdate:()=>this.textCloud.setOpacity(particles.opacity)});this.message.show();setTimeout(()=>{this.message.hide();gsap.to(particles,{opacity:0,duration:.7,ease:'power2.in',onUpdate:()=>this.textCloud.setOpacity(particles.opacity),onComplete:()=>{this.textCloud.visible=false;this.travel();}});},this.config.timing.messageDuration*1000);}
travel(){this.states.transitionTo(STATES.TRAVEL);this.dust.visible=true;const target={z:this.camera.instance.position.z};gsap.to(target,{z:2.4,duration:this.reduced?1:this.config.timing.travelDuration,ease:'power2.inOut',onUpdate:()=>this.camera.instance.position.z=target.z,onComplete:()=>this.revealUniverse()});}
revealUniverse(){this.states.transitionTo(STATES.BLACK_HOLE_REVEAL);const v={p:0};gsap.to(v,{p:1,duration:this.config.timing.blackHoleRevealDuration,ease:'power2.out',onUpdate:()=>{this.blackHole.reveal(v.p);this.flowers.reveal(Math.max(0,(v.p-.35)/.65));},onComplete:()=>this.states.transitionTo(STATES.UNIVERSE)});}
openQuote(flower,point){if(this.states.getState()!==STATES.UNIVERSE)return;this.states.transitionTo(STATES.QUOTE_FOCUS);flower.scale.setScalar(flower.userData.baseScale*1.18);this.selected=flower;this.pool.burst(point);const id=flower.userData.quoteId.replace('quote-','quote-0');this.quote.open(quotes.find(q=>q.id===id)||quotes[0]);}
closeQuote(){this.quote.close();if(this.selected)this.selected.scale.setScalar(this.selected.userData.baseScale);this.selected=null;if(this.states.getState()===STATES.QUOTE_FOCUS)this.states.transitionTo(STATES.UNIVERSE);}
applyConfig(c){this.renderer.instance.toneMappingExposure=c.general.exposure;this.camera.instance.fov=c.camera.fov;this.camera.instance.updateProjectionMatrix();this.blackHole.applyConfig(c.blackHole);this.post.applyConfig({bloomStrength:c.bloom.strength,bloomRadius:c.bloom.radius,bloomThreshold:c.bloom.threshold,lensingStrength:c.blackHole.lensingStrength*.05,exposure:c.general.exposure,quality:this.profile.name});}
update(frame){this.cloud.update(frame.elapsed);this.textCloud.update(frame.elapsed);this.dust.update(frame.elapsed);this.blackHole.update(frame);this.flowers.update(frame.elapsed,this.camera.instance);this.pool.update(frame.delta);this.morph.update(frame);if([STATES.INTRO,STATES.UNIVERSE,STATES.QUOTE_FOCUS].includes(this.states.getState()))this.camera.update(this.input.pointer,this.config,this.reduced);if(this.performance.sample(frame.delta)){this.profile=this.performance.profile;this.renderer.resize(this.profile);this.post.setQuality(this.profile.name);}this.post.render(frame.delta);}
loop=()=>{if(!this.running)return;const frame=this.clock.tick();this.update(frame);requestAnimationFrame(this.loop);};
resize(){this.renderer.resize(this.profile);this.camera.resize();this.post?.resize(innerWidth,innerHeight,this.renderer.instance.getPixelRatio());this.cloud?.setPixelRatio(this.renderer.instance.getPixelRatio());this.textCloud?.setPixelRatio(this.renderer.instance.getPixelRatio());}
restart(){gsap.globalTimeline.clear();this.closeQuote();this.states.restart();this.camera.reset(this.config);this.sunflower.object.visible=true;this.sunflower.reveal(1);this.cloud.visible=false;this.cloud.reset();this.textCloud.visible=false;this.textCloud.setOpacity(0);this.dust.visible=false;this.blackHole.reset();this.flowers.reveal(0);this.prompt.show();}
destroy(){this.running=false;gsap.globalTimeline.clear();this.keyboard?.dispose();this.editor?.dispose();this.audio.dispose();this.post?.dispose();this.sunflower?.dispose();this.cloud?.dispose();this.textCloud?.dispose();this.dust?.dispose();this.blackHole?.dispose();this.flowers?.dispose();this.pool?.dispose();this.assets.dispose();this.tracker.disposeAll();this.renderer.dispose();}}
